### ISSUE TITLE
Agprime- The page "Targhetare.ro" is not opening

### ISSUE THREAD

**Issue by chiparca81** [peviitor-ro/Scrapers_Matei#12]
**Environment**: production
**URL**: https://scrapers.peviitor.ro/
**Browser**: Chrome
**Device**: Laptop
**OS**: Windows 11

**Steps to reproduce**

1. Open the page: https://scrapers.peviitor.ro/
2. Click on "Search" button
3. Type in "agprime"
4. Click on folder "agprime"
5. Hower to logo " agprime"
6. Click on "Targhetare.ro"

**Expected result**

The page "Targhetare.ro" is opening

**Actual result**

The page "Targhetare.ro" is not opening

**Attachament**

![AgPrime- Targhetare](https://github.com/peviitor-ro/Scrapers_Matei/assets/159166761/53d519b8-78bf-4aaf-87a5-8d35cddf9dcc)

**Comment by MateiBabaua** [comment]
The company does not have a link in targetare.ro

**Comment by chiparca81** [comment]
The bug is not removed
