### ISSUE TITLE
AscentGroup- "Chisineu Cris" is not a city in Romania

### ISSUE THREAD

**Issue by chiparca81** [peviitor-ro/Scrapers_Matei#13]
**Environment**: production
**URL**: https://scrapers.peviitor.ro/
**Browser**: Chrome
**Device**: Laptop
**OS:** Windows 11

**Steps to reproduce**

1.Open the page: https://scrapers.peviitor.ro/
2.Search for "AscentGroup" Company
4.Click on folder "ascentgroup"
5.Click on "Run Scraper" button

 **Expected result**

"Chisineu Cris" is a city in Romania

**Actual result**

 "Chisineu Cris" is not a city in Romania

**Attachament**

<img width="863" alt="image" src="https://github.com/peviitor-ro/Scrapers_Matei/assets/159166761/ee691aa1-986c-40d8-9228-6adb3490419c">

**Comment by MateiBabaua** [comment]
Issue fixed.

![image](https://github.com/peviitor-ro/Scrapers_Matei/assets/146104320/379c2d53-4fb6-42ea-a1d4-c1cc35d9bd5b)
