### ISSUE TITLE
Auto1-Company's name is not "Auto1" 

### ISSUE THREAD

**Issue by chiparca81** [peviitor-ro/Scrapers_Matei#14]
Environment: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

Steps to reproduce

1.Open the page: https://scrapers.peviitor.ro/
2.Search for "Auto1" Company
4.Click on folder "auto1"
5.Hower to logo 
6.Click on "Targhetare.ro" button

Expected result

The Company's name is "Auto1"

Actual result

The Company's name is" West Auto1 Dealer SRL

Attachament

<img width="943" alt="image" src="https://github.com/peviitor-ro/Scrapers_Matei/assets/159166761/fd17d9b7-c69b-4ccd-9bba-d068060e7cb5">

**Comment by MateiBabaua** [comment]
The company Auto1 is an international company in Berlin, not in Arad

![image](https://github.com/peviitor-ro/Scrapers_Matei/assets/146104320/aa0142eb-25f1-4dc4-b17c-73ad726cd83d)
