### ISSUE TITLE
Auto1-The Company no have the graph active

### ISSUE THREAD

**Issue by chiparca81** [peviitor-ro/Scrapers_Matei#15]
Environment: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

Steps to reproduce

1.Open the page: https://scrapers.peviitor.ro/
2.Search for "Auto1" Company
4.Click on folder "auto1"

Expected result

The graph is active

Actual result

The graph is active

Attachament

<img width="901" alt="image" src="https://github.com/peviitor-ro/Scrapers_Matei/assets/159166761/1766dddf-6b37-4394-84f0-8c8d200b6c26">

**Comment by MateiBabaua** [comment]
You'll need to wait for the database to update before the graph appears

![image](https://github.com/peviitor-ro/Scrapers_Matei/assets/146104320/9cb13c96-8cf5-4d3c-90b4-bd7af23797cb)
