### ISSUE TITLE
Mhp - The message " Cluj " is displayed instead of the job locations ; - The message " No job type" is displayed instead of the job type status 

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/Scrapers_Matei#16]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

Open the URL in the browser
1.Search for " Mhp - " Company
2. Check the job locations
3. Check the job type.

EXPECTED RESULTS:

1. Job locations are the same in Scrapers-UI as on the company website.
2. Job type are the same in Scrapers-UI as on the company website.
ACTUAL RESULTS:

1. The message " Cluj " is displayed instead of the job locations
2. The message " No job type" is displayed instead of the job type status.

ATTACHMENTS:

![image](https://github.com/peviitor-ro/Scrapers_Matei/assets/71781611/9d76bfed-72bc-45cd-a943-febc9b80f5d0)

**Comment by MateiBabaua** [comment]
Issue fixed

![image](https://github.com/peviitor-ro/Scrapers_Matei/assets/146104320/fec7393d-edd7-489c-bc44-46f4518d5f32)
