### ISSUE TITLE
Auto1-The identification data from Database is different

### ISSUE THREAD

**Issue by chiparca81** [peviitor-ro/Scrapers_Matei#18]
Environment: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

Steps to reproduce

1.Open the page: https://scrapers.peviitor.ro/
2.Search for "Auto1" Company
4.Click on folder "auto1"
5.Hower to logo
6.Click on "Targhetare.ro" button

Expected result

The identification data belong to " Auto1"

Actual result

The identification data do not correspond to the company "auto 1"

Attachament

https://discord.com/channels/@me/1205121673439748106/1205188804819030058

**Comment by lalalaurentiu** [comment]
Logo fixed , attachament link is broken
