### ISSUE TITLE
Autocobalcescu- Theare are no city or job title in description

### ISSUE THREAD

**Issue by chiparca81** [peviitor-ro/Scrapers_Matei#19]
Environment: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

Steps to reproduce

1.Open the page: https://scrapers.peviitor.ro/
2.Search for "Autocobalcescu" Company
4.Click on folder "Autocobalcescu"
5.Click on "Run Scraper" button

Expected result

1.The city appear in description of jobs
2. The title appear in description of jobs

Actual result

1.The city no appear in description of jobs
2. The title no appear in description of jobs

Attachament

<img width="944" alt="image" src="https://github.com/peviitor-ro/Scrapers_Matei/assets/159166761/a487baaa-b0f3-4e6a-8dc4-855bdb1c9626">

**Comment by MateiBabaua** [comment]
Issue fixed
