### ISSUE TITLE
Cleverthech- Status "Inactive"

### ISSUE THREAD

**Issue by chiparca81** [peviitor-ro/Scrapers_Matei#20]
Environment: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

Steps to reproduce

1.Open the page: https://scrapers.peviitor.ro/
2.Search for "clever" Company
4.Click on folder "Clevertech"
5.Click on "Run Scraper" button

Expected result

The status is active

Actual result 

Trhe status is inactive

Attachament

<img width="916" alt="image" src="https://github.com/peviitor-ro/Scrapers_Matei/assets/159166761/ef3d33d5-7f1b-48d7-8898-3eddf89dff5c">

**Comment by MateiBabaua** [comment]
Issue fixed
![image](https://github.com/peviitor-ro/Scrapers_Matei/assets/146104320/4f881c43-ca4d-4aac-8d86-25208d687ba1)
