### ISSUE TITLE
Contakt- Some jobs have an error "The city is not a city in Romania"

### ISSUE THREAD

**Issue by chiparca81** [peviitor-ro/Scrapers_Matei#21]
Environment: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

Steps to reproduce

1.Open the page: https://scrapers.peviitor.ro/
2.Search for "contakt" Company
4.Click on folder "Contakt"
5.Click on "Run Scraper" button

Expected result

Cities should be displayed without errors

Actual result

An error occurs when displaying cities

Attachament

<img width="957" alt="image" src="https://github.com/peviitor-ro/Scrapers_Matei/assets/159166761/4b552900-bb73-4b4d-ab71-fa82f6badc84">

**Comment by MateiBabaua** [comment]
Issue fixed

![image](https://github.com/peviitor-ro/Scrapers_Matei/assets/146104320/ca024f1c-ba60-4c97-8579-9d79ab35253d)
