### ISSUE TITLE
Diversey- "Targhetare.ro" button is not displaying

### ISSUE THREAD

**Issue by chiparca81** [peviitor-ro/Scrapers_Matei#22]
Environment: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

Steps to reproduce

1.Open the page: https://scrapers.peviitor.ro/
2.Search for "diversey" Company
4.Click on folder "diversey"
5.Hower over  logo

Expected result

"Targhetare.ro" button is displaying

Actual result

"Targhetare.ro" button isn't displaying

Attachament

![Diversey](https://github.com/peviitor-ro/Scrapers_Matei/assets/159166761/d5626a69-0c57-4b39-82ec-f32df330f1b3)

**Comment by MateiBabaua** [comment]
The company doesn't have a link on targetare.ro
