### ISSUE TITLE
Fieldstar-Some jobs have errors "The city is not a city in Romania

### ISSUE THREAD

**Issue by chiparca81** [peviitor-ro/Scrapers_Matei#24]
Environment: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

Steps to reproduce

1.Open the page: https://scrapers.peviitor.ro/
2.Search for "fieldstar" Company
4.Click on folder "fieldstar"
5.Click on "Run Scraper" button

Expected result

Cities should be displayed without errors

Actual result

An error occurs when displaying cities

Attachament

<img width="901" alt="image" src="https://github.com/peviitor-ro/Scrapers_Matei/assets/159166761/ac7b81fd-e883-4e6f-b010-4811c7c0911a">

**Comment by MateiBabaua** [comment]
Issue fixed 
![image](https://github.com/peviitor-ro/Scrapers_Matei/assets/146104320/e7fc345d-96b9-4b35-9e51-76d8753f4cf1)
