### ISSUE TITLE
Gigroup- The number of jobs in the chart differs from the one on the website

### ISSUE THREAD

**Issue by chiparca81** [peviitor-ro/Scrapers_Matei#25]
Environment: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

Steps to reproduce

1.Open the page: https://scrapers.peviitor.ro/
2.Search for "gigroup" Company
4.Click on folder "gigroup"
5.Click on "Run Scraper" button
6. Put the cursor on the point next to the day 11.02.2024

Expected result

The number of jobs should be equal to the one on the website

Actual result

The number of jobs doesn't equals to the one the website

Attachament

![Gigroup](https://github.com/peviitor-ro/Scrapers_Matei/assets/159166761/0b9db13e-2328-4a32-be3d-c426293adfb5)

**Comment by MateiBabaua** [comment]
[image](https://github.com/peviitor-ro/Scrapers_Matei/assets/146104320/307f7cd9-d2b4-4b2c-8aca-563fd1694782)
