### ISSUE TITLE
Gmv- Status inactiv, no data in Local Storage

### ISSUE THREAD

**Issue by chiparca81** [peviitor-ro/Scrapers_Matei#26]
Environment: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

Steps to reproduce

1.Open the page: https://scrapers.peviitor.ro/
2.Search for "gmv" Company
4.Click on folder "gmv"
5.Click on "Run Scraper" button

Expected result

Status activ, data in Local Storage

Actual result

Status inactiv, no data in Local Storage

Attachament

<img width="957" alt="image" src="https://github.com/peviitor-ro/Scrapers_Matei/assets/159166761/6b8c6496-da67-483a-b264-874db5814d0b">

**Comment by MateiBabaua** [comment]
Andrei told me to rewrite the 'gmv' scraper in the new format, and now the UI needs to be modified, to find the scraper in my repository

Link: https://github.com/peviitor-ro/Scrapers_Matei/blob/main/sites/gmv_scraper.py

**Comment by lalalaurentiu** [comment]
Transfered and scraper is not working
![Image](https://github.com/peviitor-ro/Scrapers_Matei/assets/67306273/6541652a-5c72-4e26-a953-df7e5a0be6f7)
