### ISSUE TITLE
Inoveco- Jobs show an error at city "Ilfov is not a city in Romania"

### ISSUE THREAD

**Issue by chiparca81** [peviitor-ro/Scrapers_Matei#27]
Environment: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

Steps to reproduce

1.Open the page: https://scrapers.peviitor.ro/
2.Search for "inoveco" Company
4.Click on folder "inoveco"
5.Click on "Run Scraper" button

Expected result

Jobs should be displayed without errors

Actual result

An error occurs when displaying jobs

Attachament

<img width="952" alt="image" src="https://github.com/peviitor-ro/Scrapers_Matei/assets/159166761/1bc30967-3adb-4846-a3cc-79e032157828">

**Comment by MateiBabaua** [comment]
Issue fixed.
![image](https://github.com/peviitor-ro/Scrapers_Matei/assets/146104320/6353a40a-f26a-4e87-ad9b-9224ed054c3c)
