### ISSUE TITLE
Inspet-Jobs show an error at type of jobs " No job type"

### ISSUE THREAD

**Issue by chiparca81** [peviitor-ro/Scrapers_Matei#28]
Environment: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

Steps to reproduce

1.Open the page: https://scrapers.peviitor.ro/
2.Search for "inoveco" Company
4.Click on folder "inoveco"
5.Click on "Run Scraper" button

Expected result

Type of jobs should be displaing

Actual result

Type of job show an error " No job type"

Attachament

<img width="937" alt="image" src="https://github.com/peviitor-ro/Scrapers_Matei/assets/159166761/4e1798f9-d307-4ec2-af6a-c60747149b42">

**Comment by MateiBabaua** [comment]
Issue fixed
![image](https://github.com/peviitor-ro/Scrapers_Matei/assets/146104320/aa82a2fe-7053-4b32-8169-7d48f217593f)
