### ISSUE TITLE
Ados- 'No city' is displayed in the city section for all jobs

### ISSUE THREAD

**Issue by Luizalien** [peviitor-ro/Scrapers_Matei#29]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/ados/index.html
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

Open URL in browser
Run scraper 
Check the city section for all jobs

EXPECTED RESULTS:
In the city section is displayed the city name 

ACTUAL RESULTS:
In the city section "No city" is displayed

![image](https://github.com/peviitor-ro/Scrapers_Matei/assets/149939147/9dd03014-d39c-463e-96dd-044c9c0b4baf)

**Comment by MateiBabaua** [comment]
Issue fixed
![image](https://github.com/peviitor-ro/Scrapers_Matei/assets/146104320/2e55e678-b5f2-42b1-9104-753dc042671d)
