### ISSUE TITLE
Intelactsoft - All 4 jobs are listed under job type on-site although it is not specified on the company website; Company name has '_scraper' written at the end of it 

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/Scrapers_Matei#3]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/intelactsoft/index.html
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1) Open URL in browser
2) Click on 'Run Scraper' button
3) Check job type section
4) Check 'Company' section

EXPECTED RESULTS:
Job type it is not specified on scrapers.peviitor.ro if it is not specified on the company website
In 'Company' section company name is written Intelactsoft

ACTUAL RESULTS:
All 4 job have specified job type as on-site
In 'Company' section company name is written Intelactsoft_scraper

![cap4](https://github.com/peviitor-ro/Scrapers_Matei/assets/72222644/a413a21c-bd21-43fb-b476-0cf1069186f8)

**Comment by lalalaurentiu** [comment]
@MateiBabaua we put the job type only if it is present on the career page

**Comment by MateiBabaua** [comment]
Fixed.
