### ISSUE TITLE
Altimate- city misfit for "Tehnician rețele și curenți slabi" job 

### ISSUE THREAD

**Issue by Luizalien** [peviitor-ro/Scrapers_Matei#30]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/altimate/index.html
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

Open URL in browser
Run scraper
Check the city section for "Tehnician rețele și curenți slabi" job 

EXPECTED RESULTS:
In the city section is displayed Râmnicu Vâlcea

ACTUAL RESULTS:
In the city section is displayed Bucuresti

![image](https://github.com/peviitor-ro/Scrapers_Matei/assets/149939147/b70d664f-a083-4861-96bf-2ad41e189302)

**Comment by MateiBabaua** [comment]
Issue fixed
![image](https://github.com/peviitor-ro/Scrapers_Matei/assets/146104320/a9e19a5a-a28d-410f-baa8-dcfca3066e66)
