### ISSUE TITLE
Intelactsoft- Targetare link doesn't work

### ISSUE THREAD

**Issue by Luizalien** [peviitor-ro/Scrapers_Matei#31]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/src/intelactsoft/#
Browser: Google Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

Open the URL in the browser
Run scraper 
Go to logo
Click on "Tagetare" button

EXPECTED RESULTS:
The link opens on the targetare section.

ACTUAL RESULTS:
When we click on the "Targetare" button, we remain on the same page of scrapers.peviitor.ro

**Comment by MateiBabaua** [comment]
The targetare.ro's link needs to be implemented

Link: https://targetare.ro/28701654/intelligence-act-srl

**Comment by lalalaurentiu** [comment]
Fixed
