### ISSUE TITLE
Gigroup - The "Director Sucursala" job  has an error  "City is not a city in Romania"

### ISSUE THREAD

**Issue by chiparca81** [peviitor-ro/Scrapers_Matei#32]
Environment: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

Steps to reproduce

1.Open the page: https://scrapers.peviitor.ro/
2.Search for "gigroup" Company
4.Click on folder "gigroup"
5.Click on "Run Scraper" button

Expected result

Cities should be displayed without errors

Actual result

An error occurs when displaying cities

Attachament

<img width="943" alt="image" src="https://github.com/peviitor-ro/Scrapers_Matei/assets/159166761/39a3a287-2e25-45ab-8fdd-3f91d46f8261">

**Comment by MateiBabaua** [comment]
Issue fixed
