### ISSUE TITLE
Autocobalcescu- Theare are no job type in description

### ISSUE THREAD

**Issue by chiparca81** [peviitor-ro/Scrapers_Matei#33]
Environment: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

Steps to reproduce

1.Open the page: https://scrapers.peviitor.ro/
2.Search for "Autocobalcescu" Company
4.Click on folder "Autocobalcescu"
5.Click on "Run Scraper" button

Expected result

The job type appear in description of jobs

Actual result

The job type doesn't appear in description of jobs

Attachament

<img width="947" alt="image" src="https://github.com/peviitor-ro/Scrapers_Matei/assets/159166761/5e4937cf-2e50-496e-aa99-b4a77bb27515">

**Comment by MateiBabaua** [comment]
Issue fixed.
