### ISSUE TITLE
Clevertech- Theare are no job on " pevitor.ro"

### ISSUE THREAD

**Issue by chiparca81** [peviitor-ro/Scrapers_Matei#34]
Environment: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

Steps to reproduce

1.Open the page: https://scrapers.peviitor.ro/
2.Search for "clever" Company
4.Click on folder "Clevertech"
5.Click on "Run Scraper" button
6 Click on " See jobs" button

Expected result

The jobs is displaing

Actual result

Theare are no job

Attachament

<img width="931" alt="image" src="https://github.com/peviitor-ro/Scrapers_Matei/assets/159166761/9f16f9a4-f0ce-4996-82de-a73b97d37535">

**Comment by MateiBabaua** [comment]
![image](https://github.com/peviitor-ro/Scrapers_Matei/assets/146104320/5bb6b762-1012-49a5-96d2-0ec31923e0db)
![image](https://github.com/peviitor-ro/Scrapers_Matei/assets/146104320/9b3c4d54-520f-4183-a6cb-6866ae359f53)
