### ISSUE TITLE
Maxbet - The message "Targu Mures,Piatra Neamt is not a city in Romania" is displayed instead of the job locations; - The message " No job type" is displayed instead of the job type status 

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/Scrapers_Matei#36]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for " Maxbet" Company
3. Check the job locations
4. Check the job type.

EXPECTED RESULTS:

Job locations are the same in Scrapers-UI as on the company website.
Job type are the same in Scrapers-UI as on the company website.

ACTUAL RESULTS:

The message "Targu Mures, Piatra Neamt is not a city in Romania" is displayed instead of the job locations; 
The message " No job type" is displayed instead of the job type status.

ATTACHMENTS:

![image](https://github.com/peviitor-ro/Scrapers_Matei/assets/71781611/40a1c390-7c90-470b-9373-65c5bfdc72e4)
![Screenshot 2024-02-13 110540](https://github.com/peviitor-ro/Scrapers_Matei/assets/71781611/7cbb6b7c-8921-457e-a0a4-3d9d02fe4172)

**Comment by MateiBabaua** [comment]
Issue fixed.
