### ISSUE TITLE
Leviatan- wrong Targetare link

### ISSUE THREAD

**Issue by Luizalien** [peviitor-ro/Scrapers_Matei#38]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/src/leviatan/
Browser: Google Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

Open the URL in the browser
Run scraper
Go to logo
Click on "Tagetare.ro" button

EXPECTED RESULTS:
The Targetare.ro button links to LEVIATAN DESIGN SRL on Targetare.ro site
https://targetare.ro/30329499/leviatan-design-srl

ACTUAL RESULTS:
The Targetare.ro button links to LEVIATAN CONSTRUCT SRL on Targetare.ro site

![image](https://github.com/peviitor-ro/Scrapers_Matei/assets/149939147/597a7f74-791e-4917-9257-cc3ca2ad15bb)
![image](https://github.com/peviitor-ro/Scrapers_Matei/assets/149939147/955e5a23-8418-4c4f-803e-3ee415cea13d)
![image](https://github.com/peviitor-ro/Scrapers_Matei/assets/149939147/53765aee-e1f8-4e33-9672-58504da3cc20)

**Comment by lalalaurentiu** [comment]
Fixed
