### ISSUE TITLE
Erpahr- Multiple error at job locations

### ISSUE THREAD

**Issue by Luizalien** [peviitor-ro/Scrapers_Matei#39]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/src/erpahr/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

Open the URL in the browser
Check the job locations

EXPECTED RESULTS:

Job locations are the same in Scrapers-UI as on the company website.

ACTUAL RESULTS:

The messages "Băicoi, Ploiești, Filipestii De Padure is not a city in Romania", "Ploiești, Prahova is not a city in Romania", "Pitești, Poiana Lacului is not a city in Romania" are displayed instead of the job locations.

![image](https://github.com/peviitor-ro/Scrapers_Matei/assets/149939147/e888b896-2a36-42f2-afa7-e0b1cc43efeb)

**Comment by MateiBabaua** [comment]
Issue fixed
