### ISSUE TITLE
Intelactsoft - Targetare.ro link does not redirect user to the correct page

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/Scrapers_Matei#4]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/intelactsoft/index.html
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1) Open URL in browser
2) Go to company logo
3) Click on Targetare.ro link

EXPECTED RESULTS:
User is redirected to targetare.ro

ACTUAL RESULTS:
User is redirected to https://scrapers.peviitor.ro/src/intelactsoft/index.html

![cap5](https://github.com/peviitor-ro/Scrapers_Matei/assets/72222644/76cdb3c4-cfd8-4322-8d20-3bb566fefaa9)

**Comment by lalalaurentiu** [comment]
The company does not have a link in targetare.ro
