### ISSUE TITLE
Karcher- Job description displaing with error "No job type"

### ISSUE THREAD

**Issue by chiparca81** [peviitor-ro/Scrapers_Matei#40]
Environment: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

Steps to reproduce

1.Open the page: https://scrapers.peviitor.ro/
2.Search for "Karcher" Company
3.Click on folder "karcher"
4.Click on "Run Scraper" button

Expected result

Job description displaing without errors

Actual result

Job description displaing with error "No job type"

Attachament

<img width="934" alt="image" src="https://github.com/peviitor-ro/Scrapers_Matei/assets/159166761/7639d7f1-853d-4da1-a253-9e23740e5870">

**Comment by MateiBabaua** [comment]
Issue fixed
![image](https://github.com/peviitor-ro/Scrapers_Matei/assets/146104320/069017ed-7240-4f9b-95a6-5d21504102b5)
