### ISSUE TITLE
Igt- The chart is empty

### ISSUE THREAD

**Issue by chiparca81** [peviitor-ro/Scrapers_Matei#47]
Environment: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

Steps to reproduce

1.Open the page: https://scrapers.peviitor.ro/
2.Search for "igt" Company
4.Click on folder "igt"

Expected result

The chart displays information

Actual result

The chart is empty

Attachament

<img width="946" alt="image" src="https://github.com/peviitor-ro/Scrapers_Matei/assets/159166761/2278446e-729e-415a-8821-1cbfd31bf673">

**Comment by MateiBabaua** [comment]
Issue fixed, the chart will start working from today onwards. Please verify it over the next few days as well.
