### ISSUE TITLE
Igt- Jobs are not added on the page "https://peviitor.ro/"

### ISSUE THREAD

**Issue by chiparca81** [peviitor-ro/Scrapers_Matei#48]
Environment: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

Steps to reproduce

1.Open the page: https://scrapers.peviitor.ro/
2.Search for "igt" Company
4.Click on folder "igt"
5. Click on " See jobs" button"

Expected result

The jobs are displayed on the page

Actual result

The jobs are  not displayed on the page

Attachament

<img width="949" alt="image" src="https://github.com/peviitor-ro/Scrapers_Matei/assets/159166761/4bae86cc-777a-47eb-9abb-34dbfba3be6b">

**Comment by MateiBabaua** [comment]
Issue fixed.
![image](https://github.com/peviitor-ro/Scrapers_Matei/assets/146104320/022ef272-0f96-4a1c-ae02-cae3a663820a)
