### ISSUE TITLE
Unix - Status Database Error

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/Scrapers_Matei#5]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for " Unix  " Company.
3. Click on the "Run scraper"

EXPECTED RESULTS:
" Run scraper" is working and Status is " Active"

ACTUAL RESULTS:
Status Database Error

![image](https://github.com/peviitor-ro/Scrapers_Matei/assets/71781611/ad30efa1-7067-444d-9e3d-bb3cac43edcb)

**Comment by MateiBabaua** [comment]
I solved the problem with the token

**Comment by Geo843** [comment]
Re-tested, Status Active.
