### ISSUE TITLE
Gmv-Jobs show an error at type of jobs " No job type"

### ISSUE THREAD

**Issue by chiparca81** [peviitor-ro/Scrapers_Matei#54]
Environment: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

Steps to reproduce

1.Open the page: https://scrapers.peviitor.ro/
2.Search for "Gmv" Company
3.Click on folder "Gmv"
4.Click on "Run Scraper" button

Expected result

Type of jobs should be displaing

Actual result

Type of job show an error " No job type"

Attachament

<img width="944" alt="image" src="https://github.com/peviitor-ro/Scrapers_Matei/assets/159166761/72fe8787-34b4-4cc7-a7ec-e286e7b93bbc">

**Comment by MateiBabaua** [comment]
Issue fixed.
