### ISSUE TITLE
Erphahr- Theare is "No job type" error

### ISSUE THREAD

**Issue by chiparca81** [peviitor-ro/Scrapers_Matei#56]
Environment: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

Steps to reproduce

1.Open the page: https://scrapers.peviitor.ro/
2.Search for "Erpahr" Company
3.Click on folder "Erpahr"
4.Click on "Run scaper"

Expected result

The job type is displayed

Actual result

The job type is not displayed

Attachament

<img width="960" alt="image" src="https://github.com/peviitor-ro/Scrapers_Matei/assets/159166761/f0c3b309-185a-4f08-8419-09d3bd3845be">

**Comment by MateiBabaua** [comment]
Issue fixed
