### ISSUE TITLE
"TemaEnergy" - Logo is not displayed on site peviitor.ro

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/Scrapers_Matei#6]
ENVIRONMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1.Open URL peviitor.ro 
2.Put the company's name "TemaEnergy" in the search field.
3.Click Enter.

EXPECTED RESULTS:

"TemaEnergy" - The Logo appears on the site "peviitor.ro" 

ACTUAL RESULTS:

"TemaEnergy" -The Logo is not displayed on site peviitor.ro

ATTACHMENTS:

![image](https://github.com/peviitor-ro/Scrapers_Matei/assets/71781611/3daa9ef1-5f50-4dcd-ad05-7793951b4663)

**Comment by MateiBabaua** [comment]
Try to wait a little longer until the website logos load.
![image](https://github.com/peviitor-ro/Scrapers_Matei/assets/146104320/2565a6e4-442e-47a3-9857-0db526cc7d55)
