### ISSUE TITLE
Tehnoglobal - The message "Cluj  is not a city in Romania" is displayed instead of the job locations ; Job type - not defined 

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/Scrapers_Matei#7]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1.Open the URL in the browser
2. Search for "Tehnoglobal" Company
3. Open "Run Scrapers" button
4. Check the job types

EXPECTED RESULTS:
The  locations are the same in Scrapers-UI as on the company website
The job types  match the information provided by the official website.

ACTUAL RESULTS:

The message "Cluj  is not a city in Romania" is displayed instead of the job locations ; 
Job type - not defined 

![image](https://github.com/peviitor-ro/Scrapers_Matei/assets/71781611/07183c36-179a-467e-8bf4-33b35c32004e)

![image](https://github.com/peviitor-ro/Scrapers_Matei/assets/71781611/f7b5f4fd-e7a1-4715-8151-9825b36dd3a0)

![image](https://github.com/peviitor-ro/Scrapers_Matei/assets/71781611/54cafcca-0c1a-45fd-8d96-3cc73507ce0d)

**Comment by MateiBabaua** [comment]
Issue fixed.

![image](https://github.com/peviitor-ro/Scrapers_Matei/assets/146104320/acef19e3-8782-4b97-922c-5aaea5adb7a6)

**Comment by Geo843** [comment]
The second position isn't fixed.
Can you help me?

![Screenshot 2024-02-07 153702](https://github.com/peviitor-ro/Scrapers_Matei/assets/71781611/afe824d0-aa46-434a-941c-2b63e95d791e)
