### ISSUE TITLE
Saintgobain -  The message " No city"  is displayed instead of the job locations ; - The message " No job type" is displayed instead of the job type status.

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/Scrapers_Matei#8]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for " Saintgobain " Company
3. Check the job locations
5. Check the job type.

EXPECTED RESULTS:

1. Job locations are the same in Scrapers-UI as on the company website.
2. Job type are the same in Scrapers-UI as on the company website.

ACTUAL RESULTS:
1. The message " No city"  is displayed instead of the job locations ; 
 2. The message " No job type" is displayed instead of the job type status.

ATTACHMENTS: 

![image](https://github.com/peviitor-ro/Scrapers_Matei/assets/71781611/20fef56d-2a8b-4d87-8d98-2dd19277a319)

![image](https://github.com/peviitor-ro/Scrapers_Matei/assets/71781611/ac602b1e-ccf6-4233-96e9-d9aa8a6c9ea4)

![image](https://github.com/peviitor-ro/Scrapers_Matei/assets/71781611/052d1e0b-3969-40a8-acaa-3ab054fb4836)

**Comment by MateiBabaua** [comment]
The issue with the location has been resolved
