### ISSUE TITLE
Unix - The message " No type job" is displayed on the job type status for all jobs.

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/Scrapers_Matei#9]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for " Unix " Company
3. Click Run Scraper button
4. Check the job type status

EXPECTED RESULTS:
Job type status  are the same in Scrapers-UI as on the company website.

ACTUAL RESULTS:
 The message " No type job" is displayed on the job type status.

ATTACHMENTS:

![image](https://github.com/peviitor-ro/Scrapers_Matei/assets/71781611/60acb281-3cb6-4278-8636-31a31319d445)

![image](https://github.com/peviitor-ro/Scrapers_Matei/assets/71781611/b588dcf6-e112-4007-a525-aaf77eea56ce)

![image](https://github.com/peviitor-ro/Scrapers_Matei/assets/71781611/756d47f3-8d75-4f08-a2d6-d3f7b12d2b2d)

**Comment by MateiBabaua** [comment]
Issue fixed. 
![image](https://github.com/peviitor-ro/Scrapers_Matei/assets/146104320/0b2eccce-d450-4190-a2c8-3a75ffd65f49)
